
# ===================================================================
# Spring Boot configuration for the "dev" profile.
#
# This configuration overrides the application.yml file.
# ===================================================================

# ===================================================================
# Standard Spring Boot properties.
# Full reference is available at:
# http://docs.spring.io/spring-boot/docs/current/reference/html/common-application-properties.html
# ===================================================================

spring:
  activate:
    on-profile: dev
  datasource:
    type: com.zaxxer.hikari.HikariDataSource
    url: jdbc:h2:mem:internal;DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=FALSE;INIT=CREATE SCHEMA IF NOT EXISTS inpowered
    username: sa
    password:
    hikari:
      poolName: Hikari
      auto-commit: false
  h2:
    console:
      enabled: false
  jpa:
    database: H2
    show-sql: false
    properties:
      hibernate.default_schema: audit
      hibernate.cache.use_second_level_cache: false
      hibernate.cache.use_query_cache: false
